config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :gossips
get "gossips/new"
get "gossips/index"
root "gossips#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello"
  end

  def gossip

  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip
    else
      render "new"
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def update
  @gossip = Gossip.find(params[:id])

  if @gossip.update(gossip_params)
    redirect_to @gossip
  else
    render 'edit'
  end
end


def destroy
  @gossip = Gossip.find(params[:id])
  @gossip.destroy
  redirect_to gossips_path
end

def index
     @gossips = Gossip.all
end
  private
    def gossip_params
      params.require(:gossip).permit(:anonymous_author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.2.8.min.css"/>

<h1>Edit gossip</h1>

<%= form_with(model: @gossip) do |form| %>

  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> prohibited
        this gossip from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :anonymous_author %><br>
    <%= form.text_field :anonymous_author %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<h1>Listing GOSSSIP</h1>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.2.8.min.css"/>
<%= link_to 'Create', new_gossip_path %>
<table>
  <tr>
    <th>anonymous_author :</th>
    <th> Content</th>
  </tr>

  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Show', gossip_path(gossip) %></td>
      <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Destroy', gossip_path(gossip),
            method: :delete,
            data: { confirm: 'REALLY ?????' } %></td>
    </tr>
  <% end %>
</table>

app/views/gossips/new.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.2.8.min.css"/>

<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<p>Anonymous author (lol) : </br>
  <%= f.text_field :anonymous_author %> </br>
Content : </br>
  <%= f.text_area :content %></br>
  <%= f.submit "Create" %></p>
<% end %>

app/views/gossips/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.2.8.min.css"/>

<p>
  <strong>anonymous_author:</strong>
  <%= @gossip.anonymous_author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>